Added new service to provision MyQ
CESNET/perun-services pull request #570
Opened 2021-02-25 15:14 UTC by rosinec

- generates CSV import
- sends to a share

2021-03-04 19:15 UTC, zlamalp requested changes

2021-03-04 19:15 UTC, zlamalp commented on send/myq_printsvc
> +SERVICE_NAME="safeq"
`safeq` -> `myq_printsvc`

2021-06-08 13:12 UTC, stavamichal commented on gen/myq_printsvc
> +	my $resourceName = $data->getResourceAttributeValue(resource => $resourceId, attrName => $A_R_NAME);
Is resource really represented in the external system by its name in the Perun? It should be an attribute on the resource IMO.

2021-08-23 11:41 UTC, zlamalp commented
Implementation is replaced with #626. Closing this one.

2021-08-23 11:41 UTC, closed without merging