Added generic_send in Python
CESNET/perun-services pull request #586
Opened 2021-03-18 12:29 UTC by metodej

- generic_send was rewritten in Python

2021-03-30 06:50 UTC, cuadradek requested changes

2021-03-30 06:50 UTC, cuadradek commented on send/generic_send.py
> +perun_key = "/etc/perun/ssl/perun-send.key"
Please add:
`perun_chain="/etc/perun/ssl/perun-send.chain"`

2021-03-30 06:50 UTC, cuadradek commented on send/generic_send.py
> +			perun_cert_setting = "--cert " + perun_cert + " --key " + perun_key
Please, change this to:
```
if os.access(perun_cert, os.R_OK) and os.access(perun_key, os.R_OK) and os.access(perun_chain, os.R_OK):
	perun_cert_setting = "--cert " + perun_cert + " --key " + perun_key " --cacert " + perun_chain
```

2021-03-30 08:19 UTC, martin-kuba commented
This implementation is not more secure than the original in bash, because it still uses shell parsing. A secure implementation should create a new process by passing an array of arguments instead of a string.

2021-04-12 08:12 UTC, cuadradek approved these changes

2021-04-15 09:34 UTC, merged