Services arcgis_mu, hadoop*, hml_json edited to use hashed data
CESNET/perun-services pull request #590
Opened 2021-04-13 08:24 UTC by cuadradek

- Services arcgis_mu, hadoop_hbase, hadoop_hdfs and hml_json are now
using getHashedHierarchicalData.
- Services arcgis_mu and hml_json were not manually tested.

2021-04-14 09:46 UTC, Johaney-s approved these changes

2021-04-15 08:20 UTC, balcirakpeter requested changes
Please update the version also for the script arcgis_mu.
Please check at least if all scripts can be compiled (when you cannot test them) if you haven't done so already.

2021-04-15 08:20 UTC, balcirakpeter commented on gen/hml_json
> +foreach my $resourceId ($data->getResourceIds()) {
Again `getMemberIdsForFacility`

2021-04-15 09:55 UTC, cuadradek commented on gen/hadoop_hbase
> +foreach my $resourceId ($data->getResourceIds()) {
Done

2021-04-15 09:56 UTC, cuadradek commented on gen/hadoop_hdfs
> +foreach my $resourceId ($data->getResourceIds()) {
Done

2021-04-15 09:56 UTC, cuadradek commented on gen/hml_json
> +foreach my $resourceId ($data->getResourceIds()) {
Done

2021-04-15 09:57 UTC, cuadradek commented
All scripts can be compiled

2021-04-15 10:30 UTC, balcirakpeter approved these changes

2021-04-16 09:12 UTC, merged