Hierarchical groups ucn ad
CESNET/perun-services pull request #594
Opened 2021-04-19 15:37 UTC by rosinec

Supporting three different group types in UCN AD.
- Tree structure,
- Workplace,
- Standard resource==group mode.

2021-04-20 07:23 UTC, zlamalp requested changes

2021-04-20 08:38 UTC, rosinec commented on gen/ad_group_mu_ucn
> +my $data = perunServicesInit::getHashedDataWithGroups();
Yep, you are right. Expired group members should be still excluded. Tnx.

2021-04-20 12:13 UTC, zlamalp approved these changes

2021-08-31 18:38 UTC, zlamalp commented
These changes were merged as part of #627.

2021-08-31 18:38 UTC, closed without merging