k5login_root dest_file configurable
CESNET/perun-services pull request #604
Opened 2021-06-15 08:41 UTC by balcirakpeter

- Add possibility to change destination file (default is /root/.k5login)

2021-06-15 09:16 UTC, cuadradek approved these changes

2021-06-16 18:15 UTC, zlamalp requested changes

2021-06-16 18:15 UTC, zlamalp commented on slave/process-k5login-root/bin/process-k5login_root.sh
> +PROTOCOL_VERSION='3.0.1'
Please do not modify `PROTOCOL_VERSION` as format of data has not changed.

2021-06-18 12:53 UTC, zlamalp approved these changes

2021-06-24 06:58 UTC, merged