perf(gen): Hashed data - pkinit, rt*, safeq*
CESNET/perun-services pull request #612
Opened 2021-07-02 09:05 UTC by cuadradek

Services pkinit, rt, rt_bbmri, safeq and safeq5 are now using
getHashedHierarchicalData.

2021-07-07 08:57 UTC, Johaney-s approved these changes
looks good

2021-07-08 17:28 UTC, metodej approved these changes
It looks great, I have just a nitpick I think it would be nice to be consistent in parameters ordering in `get*AttributeValue` methods...

2021-07-08 21:12 UTC, zlamalp requested changes

2021-07-08 21:12 UTC, zlamalp commented on gen/safeq
> +	my $memberId = shift;
See where you print `role:` in LDIF file. You can probably use `sort keys ...`  to get comparable outputs. It's same for `billingcode:` or `card:` fields.

2021-07-09 06:13 UTC, zlamalp commented on gen/safeq
> +	my $memberId = shift;
I'm waiting for confirmation from service owner that we can sort those attributes, so please wait with that cahnge. Also it seems, that `safeq5` version can be deleted instead - also waiting for confirmation, so we won't merge this yet.

2021-08-12 08:44 UTC, merged