Ad admin
CESNET/perun-services pull request #632
Opened 2021-08-30 07:47 UTC by Vojtech-Sassmann

* Added scripts for ad_admin_user_mu_ucn and ad_admin_group_mu_ucn services.
* These services are used to manage privileged users and their groups in the ad. 
* Privileged users are users with the `mu-adm` login.

2021-11-01 09:52 UTC, balcirakpeter requested changes

2021-11-01 09:52 UTC, balcirakpeter commented on gen/ad_admin_user_mu_ucn
> +sub checkBase64 {
Not used subroutine

2021-11-01 09:52 UTC, balcirakpeter commented on send/ad_admin_group_mu_ucn
> +			# NOT REMOVING GROUPS IN UCN AD
You can remove this commented part

2021-11-01 09:52 UTC, balcirakpeter commented on send/ad_admin_group_mu_ucn
> +			#@to_be_removed = grep(/OU=(Users).*/, @to_be_removed);
You can remove the comment

2021-11-01 09:52 UTC, balcirakpeter commented on send/ad_admin_user_mu_ucn
> +			#print "is_uac_enabled == 1 for user: " . $login . "\n";
You can remove the comment

2021-11-05 10:20 UTC, balcirakpeter approved these changes

2021-11-12 10:45 UTC, metodej approved these changes

2021-11-12 10:45 UTC, merged