feat(openstack_projects): extend service to include grace period functionality
CESNET/perun-services pull request #665
Opened 2022-02-23 10:53 UTC by xflord

2022-03-02 11:26 UTC, Johaney-s approved these changes

2022-03-03 09:23 UTC, cuadradek requested changes

2022-03-03 09:23 UTC, cuadradek commented on gen/openstack_projects
> +			if ($isPersonalProjectGracePeriod && $status eq $STATUS_VALID && $groupStatus eq $STATUS_VALID) {
We discussed this and decided that we should check only group status in this case - if the member is not valid in VO, but he is active in the grace period group, we should still process him and mark him as invalid.

2022-03-03 09:23 UTC, cuadradek commented on gen/openstack_projects
> +				$users->{$identifier}->{'gp_status'} = ($status eq $STATUS_VALID && $groupStatus eq $STATUS_VALID);
```suggestion
				$users->{$identifier}->{'gp_status'} = $groupStatus eq $STATUS_VALID;
```
Same here.

2022-03-10 16:17 UTC, cuadradek approved these changes

2022-03-10 16:18 UTC, merged