feat(gen): kerberos_renewal_principals defines resource by destination file
CESNET/perun-services pull request #667
Opened 2022-03-01 14:37 UTC by sarkapalkovicova

Split resource data to separate files by using attribute kerberosPrincipalsFileSuffix.

2022-03-02 10:15 UTC, zlamalp requested changes

2022-03-02 10:15 UTC, zlamalp commented on slave/process-kerberos-renewal-principals/bin/process-kerberos_renewal_principals.sh
> +		if ! rm "$DST_DIR"*; then
I'm afraid, that destination folder contains also other files of service configuration, so we should only delete files with `kerberos_renewal_principals` prefix in the destination folder.

2022-03-02 11:29 UTC, Johaney-s commented
one more thing i just realized - at some point we decided to give commit scopes for perun-services repo by the name of the service, not gen/send/slave. please update it in the commit message, i'll update the documentation

2022-03-03 07:48 UTC, Johaney-s approved these changes

2022-03-03 08:09 UTC, zlamalp requested changes
Also please squash the commits into single feat commit.

2022-03-03 08:09 UTC, zlamalp commented on slave/process-kerberos-renewal-principals/changelog
> +  * Script copies them to the destination directory and deletes unnecessary ones.
This line is too long, changelog "content" lines are limited to 80 chars.

2022-03-03 10:17 UTC, zlamalp approved these changes

2022-03-03 11:04 UTC, merged