feat(send): atlassian_mu services in Python
CESNET/perun-services pull request #774
Opened 2023-04-04 11:54 UTC by Kuliak

* atlassian_mu script rewritten into Python using send_lib library
* atlassian_mu_process.pl file is not part of this change

2023-04-05 10:26 UTC, xflord requested changes

2023-04-05 10:26 UTC, xflord commented on send/atlassian_mu
> +def check_input_args():
please use send_lib.check_input_fields() along with check_destination_type_allowed() and check_destination_format()

2023-04-05 10:26 UTC, xflord commented on send/atlassian_mu
> +	tempDir = send_lib.prepare_temporary_directory()
```suggestion
	with send_lib.prepare_temporary_directory() as tmpDir:
```
Please make sure to handle resources carefully

2023-04-05 16:23 UTC, mattjoke approved these changes
:+1:

2023-04-14 08:59 UTC, xflord approved these changes
ok to merge if tested

2023-04-20 11:17 UTC, xflord commented
While testing I fixed a couple bugs step by step to thoroughly test, ended up fixing the whole thing, whoops. https://github.com/CESNET/perun-services/pull/78

2023-04-20 18:11 UTC, xflord commented
merged as part of https://github.com/CESNET/perun-services/pull/780

2023-04-20 18:11 UTC, closed without merging