feat(feudal): rewrite feudal send script to python
CESNET/perun-services pull request #783
Opened 2023-05-02 10:35 UTC by xflord

2023-05-11 08:02 UTC, mattjoke approved these changes
Looks good, if tested👍

2023-05-18 06:30 UTC, balcirakpeter requested changes

2023-05-18 06:30 UTC, balcirakpeter commented on send/feudal.py
> +#!/usr/bin/env python3.7
```suggestion
#!/usr/bin/env python3
```

2023-05-18 06:30 UTC, balcirakpeter commented on send/feudal.py
> +auth = (credentials.split(' ')[0], credentials.split(' ')[1])
```suggestion
auth = (credentials.split(':')[0], credentials.split(':')[1])
```

2023-05-18 06:30 UTC, balcirakpeter commented on send/feudal.py
> +send_lib.create_lock(SERVICE_NAME, destination)
This does not work as the destination contains `//`. Overall we need to escape such characters in the `send_lib.py` so we do not encounter the same problem next time. Can you please add the escaping there?

2023-05-19 06:34 UTC, balcirakpeter commented on send/feudal.py
> +send_lib.create_lock(SERVICE_NAME, destination)
```suggestion
send_lib.create_lock(SERVICE_NAME, re.sub(r'^https?://', '', destination))
```

2023-05-19 06:36 UTC, merged