feat(o365_mu_ukb_forward_status): add new service
CESNET/perun-services pull request #827
Opened 2023-09-15 09:23 UTC by kofzera

- Added gen, send and slave scripts for new service.
- The service is a copy of o365_mu_account_status service.

2023-09-18 06:24 UTC, xflord requested changes
Please also create the initial changelog entry

2023-09-18 20:16 UTC, Johaney-s commented
The scripts should be uploaded as executable files

2023-09-19 07:10 UTC, Johaney-s approved these changes

2023-09-19 16:28 UTC, xflord approved these changes

2023-09-19 16:29 UTC, merged